image: mehdisfdc/sfdx-cli #image with sfdx installed


#===DEFINITIONS===
definitions:
 
scripts:
 decryptCertificate: &decryptCertificate openssl aes-256-cbc -d -md md5 -in $SERVER_KEY_PATH -out build/server.key -k $SERVER_KEY_PASSWORD
 authToOrg: &authToOrg sfdx force:auth:jwt:grant -s -i $CONSUMERKEY -f build/server.key -u $USERNAME -r $INSTANCE_URL
 assignEnvVar: &assignEnvVar export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true && export SFDX_DOMAIN_RETRY=300 && export SFDX_DISABLE_APP_HUB=true && export SFDX_LOG_LEVEL=DEBUG
 removeScratchOnlyFolders: &removeScratchOnlyFolders rm -rf force-app/main/default/namedCredentials/
 deploy: &deploy sfdx force:source:deploy -p force-app -w 15
 deployAndTest: &deployAndTest sfdx force:source:deploy -p force-app -l RunLocalTests -w 15
 deployCheckOnly: &deployCheckOnly sfdx force:source:deploy -c -p force-app -l RunLocalTests -w 15

 
 steps:
  
    - step: &pmd-check
        name: Code Quality - PMD
        script:
          #===Download PMD===
          - wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.16.0/pmd-bin-6.16.0.zip
          - unzip pmd-bin-6.16.0.zip
          #===Make sure there is no PMD error with a high priority===
          - pmd-bin-6.16.0/bin/run.sh pmd -minimumpriority $PMD_MINIMUM_PRIORITY -d force-app -R custom-apex-rules.xml -f text -l apex

    - step: &scratch-check
        name: Scratch org Push & Test
        script:
          #===assign variables===
          - *assignEnvVar
          - export USERNAME=$PROD_USERNAME
          - export CONSUMERKEY=$PROD_CONSUMERKEY
          - export INSTANCE_URL=https://login.salesforce.com
          - export SERVER_KEY_PATH=build/PROD_server.key.enc
          - export SERVER_KEY_PASSWORD=$PROD_KEY_PASSWORD
          #===login to Dev Hub===
          - *decryptCertificate
          - *authToOrg
          #===setup scratch org===
          - sfdx force:org:create -v $USERNAME --setdefaultusername --definitionfile config/project-scratch-def.json --setalias ciorg --wait 10 --durationdays 1
          - sfdx force:org:display -u ciorg
          - sfdx force:source:push -u ciorg --json
          #===get test results===
          - sfdx force:apex:test:run -u ciorg --wait 10
          #===delete scratch org===
          - sfdx force:org:delete -u ciorg -p

    - step: &ci-validate
        name: CI sandbox Check-only 
        script:
          #===assign variables===
          - *assignEnvVar
          - export USERNAME=$CI_USERNAME
          - export CONSUMERKEY=$CI_CONSUMERKEY
          - export INSTANCE_URL=https://test.salesforce.com
          - export SERVER_KEY_PATH=build/ci_server.key.enc
          - export SERVER_KEY_PASSWORD=$CI_KEY_PASSWORD
          #===remove env specific metadata===
          - *removeScratchOnlyFolders
          #===auth with target===
          - *decryptCertificate
          - *authToOrg
          #===deploy===
          - *deployCheckOnly

    - step: &integ-deploy
        name: Deploy to INTEG org
        script:
          #===assign variables===
          - *assignEnvVar
          - export USERNAME=$INTEG_USERNAME
          - export CONSUMERKEY=$INTEG_CONSUMERKEY
          - export INSTANCE_URL=https://test.salesforce.com
          - export SERVER_KEY_PATH=build/integ_server.key.enc
          - export SERVER_KEY_PASSWORD=$INTEG_KEY_PASSWORD
          #===remove env specific metadata===
          - *removeScratchOnlyFolders
          #===auth with target===
          - *decryptCertificate
          - *authToOrg
          #===deploy===
          - *deploy

    - step: &uat-deploy
        name: Deploy to UAT org
        script:
          #===assign variables===
          - *assignEnvVar
          - export USERNAME=$UAT_USERNAME
          - export CONSUMERKEY=$UAT_CONSUMERKEY
          - export INSTANCE_URL=https://test.salesforce.com
          - export SERVER_KEY_PATH=build/uat_server.key.enc
          - export SERVER_KEY_PASSWORD=$UAT_KEY_PASSWORD
          #===remove env specific metadata===
          - *removeScratchOnlyFolders
          #===auth with target===
          - *decryptCertificate
          - *authToOrg
          #===deploy===
          - *deployAndTest

    - step: &prod-deploy
        name: Deploy to PROD org
        script:
          #===assign variables===
          - *assignEnvVar
          - export USERNAME=$PROD_USERNAME
          - export CONSUMERKEY=$PROD_CONSUMERKEY
          - export INSTANCE_URL=https://login.salesforce.com
          - export SERVER_KEY_PATH=build/PROD_server.key.enc
          - export SERVER_KEY_PASSWORD=$PROD_KEY_PASSWORD
          #===remove env specific metadata===
          - *removeScratchOnlyFolders
          #===auth with target===
          - *decryptCertificate
          - *authToOrg
          #===deploy===
          - *deploy



#===PIPELINES===
pipelines:

  default: #this will run for all branches unless specificed otherwise
    - parallel:
      - step: *pmd-check
      - step: *scratch-check
      - step: *ci-validate

  branches:
    develop:
      - step: *integ-deploy
    release/*:
      - step: *uat-deploy
    master:
      - step: *prod-deploy